routes/web.php
<?php
use Illuminate\Http\Request;
use App\Mail\ContactMail;
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::resource('/', 'WelcomeController');
Route::post('/contact', function(Request $request){
    // Mail::send(new ContactMail($request));
    Mail::to('ticketdropper23@gmail.com')->send(new ContactMail($request));

    echo ('Your message has been sent. Thank you!');
    // return redirect('/');
})->name('contact');

Route::post('subscribe', function(Request $request){
    return redirect('/');
    
})->name('subscribe');

Auth::routes();
    Route::resource('ticket','TicketsController');
    Route::resource('upcoming-festivals', 'UpcomeController');
    Route::resource('ticketweb', 'TicketwebController');
    Route::resource('etix', 'EtixController');
    Route::resource('eventbrite', 'EventbriteController');
    Route::resource('selectaseat', 'SelectaseatController');
    Route::resource('ticket-business', 'TicketbusinessController');
    Route::resource('user-ticket', 'UserticketController');
    Route::resource('statistics', 'StatisticsController');
    Route::resource('email', 'EmailController');

    Route::get('/search', 'SearchController@index')->name('mainsearch');
    Route::post('/search', 'SearchController@search')->name('search');
    Route::post('/business_search', 'TicketbusinessController@search')->name('business_search');

    Route::get('/construction', function(){
        return view('pages.construction');
    })->name('construction');
    Route::get('/map', function(){
        return view('pages.map');
    })->name('map');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/cryptocurrency', function(){
        return view('pages.cryptocurrency');
    })->name('cryptocurrency');
    
    Route::get('/chat', function(){
        return view('chat');
    })->name('chat');
 
    Route::get('/calendar', function(){
        return view('pages.calendar');
    })->name('calendar');

    Route::get('/maintenance', function(){
        return view('pages.maintenance');
    })->name('maintenance');

    Route::get('/error', function(){
        return view('pages.error');
    })->name('error');

    Route::get('/comingsoon', function(){
        return view('pages.comingsoon');
    })->name('comingsoon');

    Route::get('/user_profile', function(){
        return view('pages.profile');
    })->name('user_profile');

    Route::get('/invoice', function(){
        return view('pages.invoice');
    })->name('invoice');

    Route::get('/gallery', function(){
        return view('pages.gallery');
    })->name('gallery');
        
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class=" content-area">
  <div class="page-header">
    <h4 class="page-title">Dashboard</h4>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Dashboard 1</li>
    </ol>
  </div>

  <div class="row row-cards">
    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default bg-color">
        <div class="row">
          <div class="col-4">
            <div class="circle-icon bg-primary text-center align-self-center shadow-primary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $total_count }}</h1>
              <h5 class="font-weight-normal mb-0">Registered Ticket</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-4">
            <div class="card-img-absolute circle-icon bg-secondary align-items-center text-center shadow-secondary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $upcome }}</h1>
              <h5 class="font-weight-normal mb-0">Upcoming Ticket</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-4">
            <div class="card-img-absolute  circle-icon bg-info align-items-center text-center shadow-info"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-dollar fs-30 text-white mt-4"></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">$ {{ $total_cost }}</h1>
              <h5 class="font-weight-normal mb-0">Custom Ticket Cost</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-4">
            <div class="card-img-absolute circle-icon bg-success align-items-center text-center shadow-success"><img src="assets\images\circle.svg" class="card-img-absolute"><i class=" fa fa-code-fork fs-30 text-white mt-4 "></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">7</h1>
              <h5 class="font-weight-normal mb-0">Tracked Websites</h5>
            </div>
          </div>
        </div>
        </div>
    </div>
  </div>

  <div class="row ">
    <div class="col-lg-12 col-xl-4 col-sm-12">
      <div class="card ">
        <div class="card-header">
          <div class="card-title">All Tickets</div>
        </div>
        <div class="card-body p-4">
          <div class="chats-wrap">
            <div class="chat-details mb-1 p-3">
              <h4 class="mb-0">
                <span class="h5 font-weight-normal">Ongoing Tickets</span>
                <span class="float-right p-1  btn btn-sm text-default">
                <b></b>{{ $upcome }}</span>
              </h4>
              <div class="progress progress-md mt-3">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary-gradient" style="width: 70%"></div>
              </div>
            </div>
            <div class="chat-details mb-1 p-3">
              <h4 class="mb-0">
                <span class="h5 font-weight-normal"> Custom Ticket</span>
                <span class="float-right p-1  btn btn-sm text-default">
                  <b>{{$custom_ticket}}</b></span>
              </h4>
              <div class="progress progress-md mt-3">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-info-gradient" style="width: 60%"></div>
              </div>
            </div>
            <div class="chat-details mb-1 p-3">
              <h4 class="mb-0">
                <span class="h5 font-weight-normal">Custom Price</span>
                <span class="float-right p-1  btn btn-sm text-default">
                  <b>$ {{$total_cost}}</b>
                </span>
              </h4>
              <div class="progress progress-md mt-3">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning-gradient" style="width: 47%"></div>
              </div>
            </div>
            <div class="chat-details mb-1 p-3">
              <h4 class="mb-0">
                <span class="h5 font-weight-normal">Today Cost</span>
                <span class="float-right p-1 btn btn-sm text-default">
                  <b>$ {{$today_cost}}</b>
                </span>
              </h4>
              <div class="progress progress-md mt-3">
                <div class="progress-bar progress-bar-striped progress-bar-animated  bg-success-gradient" style="width: 25%"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-12 col-xl-8 col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Tickets Report</h3>
        </div>
        <div class="card-body">
          <div id="morrisBar3" class="chartsh"></div>
          <div class="col pt-3">
            <ul class="legend align-items-center ">
              <li>
                <span class="legend-dots bg-primary"></span>Ongoing Tickets
              </li>
              <li>
                <span class="legend-dots bg-secondary"></span>Custom Tickets
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

 

  <div class="row row-cards row-deck">
    <div class="col-md-12 col-lg-12 col-xl-4">
      <div class="card clearfix">
        <div class="card-header">
            <h2 class="card-title">Profile</h2>
        </div>
          <div class="card-body p-0">
          <div class="card-body bg-primary text-white">
            <img src="{{ asset('assets\images\faces\male\photo.png') }}"   alt="" class="profile-img img-responsive center-block">
            <a href="#" class="profile-image">
              <span class="fa fa-pencil" aria-hidden="true"></span>
            </a>
            <div class="profile-label mt-3">
              <span>{{Auth::user()->name}}</span>
            </div>

            <div class="profile-stars">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              
              <span>Website Owner</span>
            </div>

            <div class="profile-since">
               {{date("F j, Y, g:i a")}}
            </div>
          </div>
                              <div class="border-bottom align-items-center">
            <div class="card-body">
              <div class="profile-details">
                <div class="list-group list-group-transparent mb-0 mail-inbox">
                  <a href="#" class="list-group-item list-group-item-action d-flex align-items-center">
                    <span class="icon mr-3"><i class="fa fa-phone-square"></i></span>Phone: <span>+1 860 966 1693</span>
                  </a>
                  <a href="#" class="list-group-item list-group-item-action d-flex align-items-center">
                    <span class="icon mr-3"><i class="fa fa-outdent"></i></span>Address: <span>40 Sutton Pl Apt 9J, NY 10022-2306</span>
                  </a>
                  <a href="#" class="list-group-item list-group-item-action d-flex align-items-center">
                    <span class="icon mr-3"><i class="fa fa-envelope-square"></i></span>Email: <span> tktundrgrnd@gmail.com</span>z
                  </a>
                </div>
              </div>
            </div>
          </div>
                              <div class="p-3">
            <div class="profile-message-btn center-block text-center">
              <a href="{{ route('email.index') }}" class="btn btn-secondary btn-block">
                <i class="fa fa-envelope"></i> Send message
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-12 col-xl-8 col-md-12">
      <div class="card ">
        <div class="card-header">
          <h5 class="card-title">Select a Seat </h5>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped card-table table-condensed mt-0 table-nowrap border">
              <thead>
                <tr>
                  <th>NO</th>
                  <th>EVENT</th>
                  <th>LOCATIONS</th>
                  <th>DATE</th>
               
                </tr>
              </thead>
              <tbody>
              <?php $i = 1 ?>
                @foreach($data as $row)
                <tr>
                        <th scope="row">{{ $i }}</th>
                        <td>{{ str_replace("'", "", $row->name) }}</td>
                        <td>{{ str_replace("'", "", $row->address) }}</td>
                        <td>{{ str_replace("'", "", $row->date) }}</td>
                 </tr>
                <?php $i+=1 ?>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer text-center">
          <a href="{{route('selectaseat.index')}}"><i class="fa fa-angle-down"></i> View More</a>
        </div>
      </div>
    </div>
  </div>
</div>  
 @endsection

resources/views/ticket.blade.php
@extends('layouts.app')

@section('content')
<div class=" content-area">
    <div class="page-header">
        <h4 class="page-title">Recorded Tickets</h4>
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Ticket</a></li>
        <li class="breadcrumb-item active" aria-current="page">Recorded Tickets</li>
        </ol>
    </div>
    <div class="row row-cards">
    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default bg-color">
        <div class="row">
          <div class="col-4">
            <div class="circle-icon bg-primary text-center align-self-center shadow-primary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $total_count}}</h1>
              <h5 class="font-weight-normal mb-0">Registerd Tickets</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-4">
            <div class="card-img-absolute circle-icon bg-secondary align-items-center text-center shadow-secondary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-dollar fs-30 text-white mt-4"></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">$ {{ $total_cost }}</h1>
              <h5 class="font-weight-normal mb-0">Total Cost</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-4">
            <div class="card-img-absolute  circle-icon bg-info align-items-center text-center shadow-info"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30 text-white mt-4"></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $today_count}}</h1>
              <h5 class="font-weight-normal mb-0">Today Ticket</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-3 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-4">
            <div class="card-img-absolute circle-icon bg-success align-items-center text-center shadow-success"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-dollar fs-30 text-white mt-4 "></i></div>
          </div>
          <div class="col-8">
            <div class="card-body p-4">
              <h1 class="mb-3">$ {{ $today_cost }}</h1>
              <h5 class="font-weight-normal mb-0">Today Price</h5>
            </div>
          </div>
        </div>
        </div>
    </div>
  </div>
    <div class="card p-5">
          <div class="content-wrapper">
                <div class="row">
                    <div class="col-md-6">
                        <h2>Hi <strong> {{Auth::user()->name}}</strong></h2>
                    </div>
                    <div class="col-md-5 text-right">
                        <a href="{{ route('ticket.create') }}"   class="btn btn-indigo"><i class="fa fa-link   "></i> New Ticket</a>
                    </div>
                </div>
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif
            <div class="table-responsive">      
                <table class="table card-table table-vcenter text-nowrap">
                    <tr>
                        <th width="10%">Image</th>
                        <th> Ticket Title</th>
                        <th>Price</th>
                        <th>Sales Date</th>
                        <th>Resales Date</th>
                        <th></th>
                        <th></th>
                        <!-- <th></th>
                        <th></th> -->
                    </tr>
                    @foreach($data as $row)
                    <tr>
                        <td><a href="{{ route('ticket.show', $row->id) }}"><img src="{{ asset('images')}}/{{ $row->image }}" class="img-thumbnail" width="75" /></a></td>
                        <td><a href="{{ route('ticket.show', $row->id) }}">{{ $row->name }}</a></td>
                        <td><a href="{{ route('ticket.show', $row->id) }}">$ {{ $row->price }}</a></td>
                        <td><a href="{{ route('ticket.show', $row->id) }}"> {{ $row->sale_date }} </a></td>
                        <td><a href="{{ route('ticket.show', $row->id) }}"> {{ $row->resale_date }} </a></td>
                        <td>
                            <a href="{{ route('ticket.edit', $row->id) }}" class="form-control btn-sm btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
                        </td>
                        <td>
                            <form action="{{ route('ticket.destroy', $row->id) }}" method="post">
                                 @csrf
                                @method('DELETE')
                                <button type="submit" class="form-control  btn btn-sm btn-danger"><i class="fa fa-trash"></i> Delete</button>
                            </form>
                         </td>
                         
                    </tr>
                    @endforeach
                </table>
                

            </div>
            <div class="row">
                <div class="col-md-12" style="padding-left:72%">
                {!! $data->links() !!}

                </div>
            </div>    
        </div>
    </div>
</div>
 

 
@endsection

resources/views/ticketcreate.blade.php
@extends('layouts.app')
@section('content')
<div class=" content-area">
  <div class="page-header">
    <h4 class="page-title">Create Ticket</h4>
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" > Ticket</li>
      <li class="breadcrumb-item"><a href="{{ route('ticket.index')}}">Custom Ticket</a></li>
      <li class="breadcrumb-item active" aria-current="page">Create ticket</li>
    </ol>
  </div>
    <div class="main-content">
          <div class="content-wrapper">
        <div class="card p-5">
            <div class="card-header">
                <h4 class="card-title" id="basic-layout-tooltip">You can add new ticket for you.</h4>
                 
            </div>
            <div class="card-content p-5">
            <div class="px-3">

                <form class="form" method="post" action="{{ route('ticket.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput1">Ticket Title</label>
                            <input type="text" id="issueinput1" class="form-control" name="name" data-toggle="tooltip"
                                data-trigger="hover" data-placement="top" data-title="Issue Title">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput2">Price</label>
                            <input type="text" id="issueinput2" class="form-control" name="price" data-toggle="tooltip"
                                data-trigger="hover" data-placement="top" data-title="Opened By">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput3">Sale Date</label>
                            <input type="date" id="issueinput3" class="form-control" name="sale_date" data-toggle="tooltip"
                                data-trigger="hover" data-placement="top" data-title="Date Opened">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput4">Resale Date</label>
                            <input type="date" id="issueinput4" class="form-control" name="resale_date" data-toggle="tooltip"
                                data-trigger="hover" data-placement="top" data-title="Date Fixed">
                            </div>
                        </div>
                    </div>
                   
                    <div class="form-group">
                    <label for="issueinput8">Description</label>
                    <textarea id="issueinput8" rows="5" class="form-control" name="description" data-toggle="tooltip"
                        data-trigger="hover" data-placement="top" data-title="Comments"></textarea>
                    </div>
                
                    <div class="row">
                        <div class="col-md-6">
                            
                        
                            <div class="form-group">
                            <label class="text-center">Select Ticket Image</label>
                                <div class=" custom-file">
                                    <input type="file" name="image" class="custom-file-input __web-inspector-hide-shortcut__" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                                    
                                    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <br>
                            <button type="submit" class=" btn btn-raised btn-primary">
                            <i class="fa fa-check-square-o"></i> Save
                            </button>
                        </div>
                        <div class="col-md-1">
                            <br>
                            <a href="{{ route('ticket.index') }}" class=" btn btn-purple"><i class="fa fa-repeat"></i> Back</a>

                        </div>
                    </div>
                    <br>
                    <!-- <div class="form-group">
                    <label for="issueinput5">Priority</label>
                    <select id="issueinput5" name="priority" class="form-control" data-toggle="tooltip" data-trigger="hover"
                        data-placement="top" data-title="Priority">
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                    </select>
                    </div> -->

                    

                    

                </div>

                
                     
                    
               
                </form>
            </div>
            </div>
        </div>
</div>
</div>
</div>
@endsection

resources/views/ticketedit.blade.php
@extends('layouts.app')
@section('content')
<div class=" content-area">
  <div class="page-header">
    <h4 class="page-title">Edit Ticket</h4>
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" > Ticket</li>
      <li class="breadcrumb-item"><a href="{{ route('ticket.index')}}">Custom Ticket</a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit ticket</li>
    </ol>
  </div>
    <div class="main-content">
          <div class="content-wrapper">
        <div class="card p-5" >
            <div class="card-header">
             
                  
           <h5 class="card-title"> You can edit your custom ticket here </h5>             
            

            </div>
            <div class="card-content">
            <div class="p-5">

                <form class="form" method="post" action="{{ route('ticket.update', $data->id) }}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput1">Ticket Title</label>
                            <input type="text" id="issueinput1" class="form-control" name="name" data-toggle="tooltip"
                                data-trigger="hover" value="{{ $data->name }}" data-placement="top" data-title="Issue Title">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput2">Price</label>
                            <input type="text" id="issueinput2" class="form-control" name="price" data-toggle="tooltip"
                                data-trigger="hover" value="{{ $data->price }}"  data-placement="top" data-title="Opened By">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput3">Sale Date</label>
                            <input type="date" id="issueinput3" value="{{ $data->sale_date }}"  class="form-control" name="sale_date" data-toggle="tooltip"
                                data-trigger="hover" data-placement="top" data-title="Date Opened">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="issueinput4">Resale Date</label>
                            <input type="date" id="issueinput4" value="{{ $data->resale_date }}"  class="form-control" name="resale_date" data-toggle="tooltip"
                                data-trigger="hover" data-placement="top" data-title="Date Fixed">
                            </div>
                        </div>
                    </div>
                   
                    <div class="form-group">
                    <label for="issueinput8">Description</label>
                    <textarea id="issueinput8" rows="5" value="{{ $data->description }}" class="form-control" name="description" data-toggle="tooltip"
                        data-trigger="hover" data-placement="top" data-title="Comments">{{$data->description}}</textarea>
                    </div>
                
                    <div class="row">
                        <div class="col-md-2">
                            <img src="{{ asset('images') }}/{{ $data->image }}" alt="element 04" width="200"   class="float-left mt-3">
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                            <label class="text-center">Select Ticket Image</label>
                                <div class=" custom-file">
                                    <input type="file" name="image"  class="custom-file-input __web-inspector-hide-shortcut__" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                                    <input type="hidden" name="hidden_image" value="{{ $data->image }}" />
                                    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <br><br>
                            <button type="submit"  class="btn btn-cyan">
                            <i class="fa fa-check-square-o"></i> Save
                            </button>
                        </div>
                        <div class="col-md-1">
                        <br><br>
                            <a href="{{ route('ticket.index') }}" class=" btn btn-purple"><i class="fa fa-repeat"></i> View all tickets</a>

                        </div>
                    </div>
                    <br>
                    <!-- <div class="form-group">
                    <label for="issueinput5">Priority</label>
                    <select id="issueinput5" name="priority" class="form-control" data-toggle="tooltip" data-trigger="hover"
                        data-placement="top" data-title="Priority">
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                    </select>
                    </div> -->

                    

                    

                </div>

                
                     
                    
               
                </form>
            </div>
            </div>
        </div>
</div>
</div>
</div>
@endsection