routes/web.php
<?php
use Illuminate\Http\Request;
use App\Mail\ContactMail;
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::resource('/', 'WelcomeController');
Route::post('/contact', function(Request $request){
    // Mail::send(new ContactMail($request));
    Mail::to('ticketdropper23@gmail.com')->send(new ContactMail($request));

    echo ('Your message has been sent. Thank you!');
    // return redirect('/');
})->name('contact');

Route::post('subscribe', function(Request $request){
    return redirect('/');
    
})->name('subscribe');

Auth::routes();
    Route::resource('ticket','TicketsController');
    Route::resource('upcoming-festivals', 'UpcomeController');
    Route::resource('ticketweb', 'TicketwebController');
    Route::resource('etix', 'EtixController');
    Route::resource('eventbrite', 'EventbriteController');
    Route::resource('selectaseat', 'SelectaseatController');
    Route::resource('ticket-business', 'TicketbusinessController');
    Route::resource('user-ticket', 'UserticketController');
    Route::resource('statistics', 'StatisticsController');
    Route::resource('email', 'EmailController');

    Route::get('/search', 'SearchController@index')->name('mainsearch');
    Route::post('/search', 'SearchController@search')->name('search');
    Route::post('/business_search', 'TicketbusinessController@search')->name('business_search');

    Route::get('/construction', function(){
        return view('pages.construction');
    })->name('construction');
    Route::get('/map', function(){
        return view('pages.map');
    })->name('map');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/cryptocurrency', function(){
        return view('pages.cryptocurrency');
    })->name('cryptocurrency');
    
    Route::get('/chat', function(){
        return view('chat');
    })->name('chat');
 
    Route::get('/calendar', function(){
        return view('pages.calendar');
    })->name('calendar');

    Route::get('/maintenance', function(){
        return view('pages.maintenance');
    })->name('maintenance');

    Route::get('/error', function(){
        return view('pages.error');
    })->name('error');

    Route::get('/comingsoon', function(){
        return view('pages.comingsoon');
    })->name('comingsoon');

    Route::get('/user_profile', function(){
        return view('pages.profile');
    })->name('user_profile');

    Route::get('/invoice', function(){
        return view('pages.invoice');
    })->name('invoice');

    Route::get('/gallery', function(){
        return view('pages.gallery');
    })->name('gallery');
        
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    //
    protected $fillable = [
        'name', 'price', 'sale_date','resale_date','image','description'
    ];
}

app/Http/Controllers/TicketsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ticket;
use App\users;
use Carbon\Carbon;


class TicketsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Ticket::latest()->paginate(8);
        $total_count = Ticket::get()->count();
        $total_cost = Ticket::get()->sum('price');
        $today_count = Ticket::get()->where('sale_date' , Carbon::now()->toDateString())->count();
        $today_cost = Ticket::get()->where('sale_date' , Carbon::now()->toDateString())->sum('price');
 
        
        return view('ticket',compact('data', 'total_count','total_cost','today_count','today_cost'))
        ->with('i', (request()->input('page', 1) - 1) * 8);;
                
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ticketcreate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    =>  'required',
            'price'     =>  'required',
            // 'image'         =>  'required|image|max:2048'
        ]);

        $image = $request->file('image');

        $new_name = rand() . '.' . $image->getClientOriginalExtension();
        $image->move(public_path('images'), $new_name);
        $form_data = array(
            'name'       =>   $request->name,
            'description'        =>   $request->description,
            'sale_date'        =>   $request->sale_date,
            'resale_date'        =>   $request->resale_date,
            'price'        =>   $request->price,
             'image'            =>   $new_name
        );

        Ticket::create($form_data);

        return redirect('ticket')->with('success', 'Data Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Ticket::findOrFail($id);
        return view('ticketview', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Ticket::findOrFail($id);
        return view('ticketedit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $image_name = $request->hidden_image;
        $image = $request->file('image');
        if($image != '')
        {
            $request->validate([
                'name'    =>  'required',
                'price'     =>  'required',
                // 'image'         =>  'image|max:2048'
            ]);

            $image_name = rand() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images'), $image_name);
        }
        else
        {
            $request->validate([
                'name'    =>  'required',
                'price'     =>  'required'
            ]);
        }

        $form_data = array(
            'name'       =>   $request->name,
            'description'        =>   $request->description,
            'sale_date'        =>   $request->sale_date,
            'resale_date'        =>   $request->resale_date,
            'price'        =>   $request->price,
            'image'            =>   $image_name
        );
  
        Ticket::whereId($id)->update($form_data);

        return redirect('ticket')->with('success', 'Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Ticket::findOrFail($id);
        $data->delete();

        return redirect('ticket')->with('success', 'Data is successfully deleted');
    }
}

resources/views/ticket/etix.blade.php
@extends('layouts.app')

@section('content')
<div class=" content-area">
    <div class="page-header">
        <h4 class="page-title">Etixes</h4>
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('ticket.index')}}">Ticket</a></li>
        <li class="breadcrumb-item active" aria-current="page">Etixes</li>
        </ol>
    </div>
    <div class="row">
    <div class="col-sm-12 col-lg-6 col-xl-4 col-md-6">
      <div class="card card-img-holder text-default bg-color">
        <div class="row">
          <div class="col-3">
            <div class="circle-icon bg-primary text-center align-self-center shadow-primary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
          </div>
          <div class="col-9">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $total_count}}</h1>
              <h5 class="font-weight-normal mb-0">Total Etix Tickets</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-8 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-2">
            <div class="card-img-absolute circle-icon bg-secondary align-items-center text-center shadow-secondary"><img src="{{ str_replace("'", "", $last_ticket[0]->img) }}" class="card-img-absolute"> </div>
          </div>
          <div class="col-10">
            
            <div class="card-body p-4">
              <h3 class="mb-3 text-primary"> {{ str_replace("'", "", $last_ticket[0]->name) }}  </h3>
              <h5 class="font-weight-normal mb-0"> Locations {{ str_replace("'", "", $last_ticket[0]->address) }}  <button class="btn btn-sm btn-outline-danger">Ongoing Ticket</button></h5>
            </div>
          </div>
        </div>
        </div>
    </div>
         
        
    </div>
    <div class="row">
        @foreach($data as $row)
        <div  class="col-md-6 col-sm-12 col-lg-6 col-xl-12">
            <div class="card">
                <div class="row">
                    <div class="col-lg-2">
                        <img src="{{ str_replace("'", "", $row->img) }}" alt="">
                    </div>
                    <div class="col-lg-10">
                        <small class="text-muted"> {{ str_replace("'", "", $row->date) }} : {{ str_replace("'", "", $row->price) }}</small>
                        <h4 class="text-primary">{{ str_replace("'", "", $row->name) }}</h4>
                        <p>{{ str_replace("'", "", $row->address) }}</p>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
        
 
<div class="row">
        <div class="col-md-12" style=" ">
        {!! $data->links() !!}

        </div>
    </div>


</div>
@endsection

resources/views/ticket/eventbrite.blade.php
@extends('layouts.app')

@section('content')
<div class=" content-area">
    <div class="page-header">
        <h4 class="page-title">EventBrites</h4>
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('ticket.index')}}">Ticket</a></li>
        <li class="breadcrumb-item active" aria-current="page">EventBrites</li>
        </ol>
    </div>
    <div class="row">
    <div class="col-sm-12 col-lg-6 col-xl-4 col-md-6">
      <div class="card card-img-holder text-default bg-color">
        <div class="row">
          <div class="col-3">
            <div class="circle-icon bg-primary text-center align-self-center shadow-primary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
          </div>
          <div class="col-9">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $total_count}}</h1>
              <h5 class="font-weight-normal mb-0">Total Upcoming Tickets</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-8 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-2">
            <div class="card-img-absolute circle-icon bg-secondary align-items-center text-center shadow-secondary"><img src="{{ str_replace("'", "", $last_ticket[0]->img) }}" class="card-img-absolute"> </div>
          </div>
          <div class="col-10">
            
            <div class="card-body p-4">
              <h3 class="mb-3 text-primary"> {{ str_replace("'", "", $last_ticket[0]->name) }} <small class="text-danger">{{ str_replace("'", "", $last_ticket[0]->date) }} </small></h3>
              <h5 class="font-weight-normal mb-0"> Locations {{ str_replace("'", "", $last_ticket[0]->address) }}  <button class="btn btn-sm btn-outline-danger">Newest Ticket</button></h5>
            </div>
          </div>
        </div>
        </div>
    </div>
         
        
    </div>
    <div class="row">
        @foreach($data as $row)
        <div  class="col-md-6 col-sm-12 col-lg-6 col-xl-12">
            <div class="card">
                <div class="row">
                    <div class="col-lg-2">
                        <img src="{{ str_replace("'", "", $row->img) }}" alt="">
                    </div>
                    <div class="col-lg-9">
                        <small class="text-muted"> {{ str_replace("'", "", $row->date) }} </small>
                        <h4 class="text-primary">{{ str_replace("'", "", $row->name) }} </h4>
                        <p>{{ str_replace("'", "", $row->address) }}</p>
                        
                    </div>
                    <div class="col-lg-1 pt-5">
                        @if( str_replace("'", "", $row->price)  == '')
                            <h4 class="text-success">Free</h4>
                        @else
                            <h4 class="text-info">${{ str_replace("'", "", $row->price) }}</h4>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
        
 
<div class="row">
        <div class="col-md-12" style=" ">
        {!! $data->links() !!}

        </div>
    </div>


</div>
@endsection

resources/views/ticket/selectaseat.blade.php
@extends('layouts.app')

@section('content')
<div class=" content-area">
    <div class="page-header">
        <h4 class="page-title">Select a Seat</h4>
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('ticket.index')}}">Ticket</a></li>
        <li class="breadcrumb-item active" aria-current="page">Select a Seat</li>
        </ol>
    </div>
    <div class="row row-cards">
    <div class="col-sm-12 col-lg-6 col-xl-4 col-md-6">
        <div class="card card-img-holder text-default bg-color">
            <div class="row">
            <div class="col-3">
                <div class="circle-icon bg-primary text-center align-self-center shadow-primary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
            </div>
            <div class="col-9">
                <div class="card-body p-4">
                <h1 class="mb-3">{{ $total_count}}</h1>
                <h5 class="font-weight-normal mb-0">Total Web Events</h5>
                </div>
            </div>
            </div>
            </div>
        </div>

        <div class="col-sm-12 col-lg-6 col-xl-8 col-md-6">
        <div class="card card-img-holder text-default">
            <div class="row">
            <div class="col-2">
                <div class="card-img-absolute circle-icon bg-secondary align-items-center text-center shadow-secondary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
            </div>
            <div class="col-10">
                
                <div class="card-body p-4">
                <h3 class="mb-3 text-primary"> {{ str_replace("'", "", $last_ticket[0]->name) }}  ( <small class="text-info">{{ str_replace("'", "", $last_ticket[0]->date) }}</small> )</h3>
                <h5 class="font-weight-normal mb-0"> Locations {{ str_replace("'", "", $last_ticket[0]->address) }}  <button class="btn btn-sm btn-outline-danger">Newest Ticket</button></h5>
                </div>
            </div>
            </div>
            </div>
        </div>
  </div>
   
  
  <div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">United States - Other Locations</h3>
            </div>
            <div class="table-responsive">
                <table class="table card-table table-vcenter text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Event</th>
                            <th>Locations</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 1 ?>
                        @foreach($data as $row)
                        <tr>
                                <th scope="row">{{ $i }}</th>
                                <td>{{ str_replace("'", "", $row->name) }}</td>
                                <td>{{ str_replace("'", "", $row->address) }}</td>
                                <td>{{ str_replace("'", "", $row->date) }}</td>
                            
                        </tr>
                        <?php $i+=1 ?>
                        @endforeach
                         
                    </tbody>
                </table>
            </div>
            <!-- table-responsive -->
        </div>
    </div>
</div>
<div class="row">
        <div class="col-md-12" style=" ">
        {!! $data->links() !!}

        </div>
    </div>


</div>
@endsection

resources/views/ticket/ticket_business.blade.php
@extends('layouts.app')
@section('content')

<div class=" content-area">
    <div class="page-header">
        <h4 class="page-title">Events</h4>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Business Ticket</a></li>
            <li class="breadcrumb-item active" aria-current="page">Events</li>
        </ol>

    </div>
    <div class="row row-cards">
        <div class="col-lg-3">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title"> Categories</div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label class="form-label mt-0">Locations</label>
                                <select name="beast" id="select-beast" class="form-control custom-select">
                                    <option value="0">--Select--</option>
                                     <option value="2">US</option>
                                    <option value="3">UK</option>
                                     
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="form-label">Human</label>
                                <select name="beast" id="select-beast1" class="form-control custom-select">
                                    <option value="0">--Select--</option>
                                    <option value="1">Western wear</option>
                                    <option value="2">Foot wear</option>
                                    <option value="3">Top wear</option>
                                    <option value="4">Bootom wear</option>
                                    <option value="5">Beuty Groming</option>
                                    <option value="6">Accessories</option>
                                    <option value="7">jewellery</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="form-label">Baby & Kids</label>
                                <select name="beast" id="select-beast2" class="form-control custom-select">
                                    <option value="0">--Select--</option>
                                    <option value="1">Boys clothing</option>
                                    <option value="2">girls Clothing</option>
                                    <option value="3">Toys</option>
                                    <option value="4">Baby Care</option>
                                    <option value="5">Kids footwear</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="form-label">Electronics</label>
                                <select name="beast" id="select-beast3" class="form-control custom-select">
                                    <option value="0">--Select--</option>
                                    <option value="1">Mobiles</option>
                                    <option value="2">Laptops</option>
                                    <option value="3">Gaming & Accessories</option>
                                    <option value="4">Health care Appliances</option>
                                </select>
                            </div>
                            <div class="form-group mb-0">
                                <label class="form-label">Sport,Books & More </label>
                                <select name="beast" id="select-beast4" class="form-control custom-select">
                                    <option value="0">--Select--</option>
                                    <option value="1">Stationery</option>
                                    <option value="2">Books</option>
                                    <option value="3">Gaming</option>
                                    <option value="4">Music</option>
                                    <option value="5">Exercise & fitness</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-group-item">
                            <header class="card-header">
                                <h2 class="card-title">Date </h2>
                            </header>
                            <div class="filter-content">
                                <div class="card-body">
                                <form>
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" value="">
                                        <span class="form-check-label">
                                            upcoming
                                        </span>
                                    </label> <!-- form-check.// -->
                                    <label class="form-check">
                                        <input class="form-check-input" type="checkbox" value="">
                                        <span class="form-check-label">
                                            This month
                                        </span>
                                    </label>  <!-- form-check.// -->
                                    <label class="form-check mb-0">
                                        <input class="form-check-input" type="checkbox" value="">
                                        <span class="form-check-label">
                                            Today
                                        </span>
                                    </label>  <!-- form-check.// -->
                                </form>
                                </div> <!-- card-body.// -->
                            </div>
                        </div> <!-- card-group-item.// -->
                    </div>
                    <div class="card">
                        <div class="card-group-item">
                            <header class="card-header">
                                <h2 class="card-title">Cost Range </h2>
                            </header>
                            <div class="filter-content">
                                <div class="card-body">
                                    <label class="form-check">
                                        <input class="form-check-input" type="radio" name="exampleRadio" value="">
                                        <span class="form-check-label">
                                            Free
                                        </span>
                                    </label>
                                    <label class="form-check">
                                        <input class="form-check-input" type="radio" name="exampleRadio" value="">
                                        <span class="form-check-label">
                                            $100 less
                                        </span>
                                    </label>
                                    <label class="form-check">
                                    <input class="form-check-input" type="radio" name="exampleRadio" value="">
                                        <span class="form-check-label">
                                            $100 more
                                        </span>
                                    </label>
                                </div> <!-- card-body.// -->
                            </div>
                        </div> <!-- card-group-item.// -->
                    </div>
                    <a href="{{ route('ticket-business.index')}}" class="btn btn-primary btn-block mb-3 ">Search</a>
                </div>
            </div>
        </div>
   
        <div class="col-lg-9">
        <form action="{{ route('business_search')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="input-group mb-5">
               
                    <input type="text" name="item" class="form-control br-tl-7 br-bl-7" placeholder="">
                    <div class="input-group-append ">
                        <button type="submit" class="btn btn-primary br-tr-7 br-br-7">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>
            <div class="row">
            @foreach($data as $row)

                <div class="col-lg-6 col-xl-4 col-md-12">
                    <div class="card item-card">
                        <div class="product-grid6  card-body">
                            <div class="product-image6">
                                <a href="#">
                                    <img class="img-fluid" src="{{ str_replace("'", "", $row->img) }}">
                                </a>
                            </div>
                            <div class="product-content text-center">
                                <h4 class="title"><a href="#">{{str_replace("'", "", $row->name)}}</a></h4>
                                @if(str_replace("'", "", $row->price) == '')
                                <div class="price">Free</div>
                                @else
                                <div class="price">$ {{str_replace("'", "", $row->price)}}</div>
                                @endif
                               
                            </div>

                            

                            <ul class="icons">
                                <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>

                                <li><a href="" data-tip="{{str_replace("'", "", $row->address)}}"><i class="fa fa-newspaper-o"></i></a></li>
                                <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-heart-o"></i></a></li>
                                <!-- <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li> -->
                            </ul>
                        </div>
                    </div>
                </div>  

            @endforeach                
            </div>
            <div class="mb-3 ">
                <div class="float-right">
                <div class="row">
                    <div class="col-md-12" style=" ">
                    {!! $data->links() !!}

                    </div>
                </div>
                </div>
            </div>
        </div>

    </div>
    </div>

@endsection

resources/views/ticket/upcome.blade.php
@extends('layouts.app')

@section('content')
<div class=" content-area">
    <div class="page-header">
        <h4 class="page-title">Upcoming Festivals</h4>
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Ticket</a></li>
        <li class="breadcrumb-item active" aria-current="page">upcoming festivals</li>
        </ol>
    </div>
    <div class="row row-cards">
    <div class="col-sm-12 col-lg-6 col-xl-4 col-md-6">
      <div class="card card-img-holder text-default bg-color">
        <div class="row">
          <div class="col-3">
            <div class="circle-icon bg-primary text-center align-self-center shadow-primary"><img src="assets\images\circle.svg" class="card-img-absolute"><i class="fa fa-wpforms fs-30  text-white mt-4"></i></div>
          </div>
          <div class="col-9">
            <div class="card-body p-4">
              <h1 class="mb-3">{{ $total_count}}</h1>
              <h5 class="font-weight-normal mb-0">Total Upcoming Tickets</h5>
            </div>
          </div>
        </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-6 col-xl-8 col-md-6">
      <div class="card card-img-holder text-default">
        <div class="row">
          <div class="col-2">
            <div class="card-img-absolute circle-icon bg-secondary align-items-center text-center shadow-secondary"><img src="{{ str_replace("'", "", $last_ticket[0]->img) }}" class="card-img-absolute"> </div>
          </div>
          <div class="col-10">
            
            <div class="card-body p-4">
              <h3 class="mb-3 text-primary"> {{ str_replace("'", "", $last_ticket[0]->name) }} <small class="text-danger">{{ str_replace("'", "", $last_ticket[0]->date) }} </small></h3>
              <h5 class="font-weight-normal mb-0"> Locations {{ str_replace("'", "", $last_ticket[0]->address) }}  <button class="btn btn-sm btn-outline-danger">Ongoing Ticket</button></h5>
            </div>
          </div>
        </div>
        </div>
    </div>

     
  </div>
  
  
  <div class="row">
  @foreach($data as $row)
    <div class="col-md-6 col-sm-12 col-lg-6 col-xl-3">
        <div class="card text-center">
            <img src="{{ str_replace("'", "", $row->img) }}" alt="img" class="br-tl-7 br-tr-7">
            <div class="card-body">
                <h4 class="mb-3">{{ str_replace("'", "", $row->name) }}</h4>
                <p> {{ str_replace("'", "", $row->address) }}</p>
                <a href="#" class="btn btn-primary">{{ str_replace("'", "", $row->date) }}</a>
            </div>
        </div>
    </div>
  @endforeach
  </div>
  <div class="row">
        <div class="col-md-12" style="padding-left:72%">
        {!! $data->links() !!}

        </div>
    </div>  


</div>
@endsection